[build]
  command = "go build -o public/main main.go && mkdir -p public/templates && cp -r static public/ && cp -r templates public/"
  publish = "public"

[build.environment]
  GO_VERSION = "1.21"  # Adjust based on your compatibility
  NETLIFY_BUILD_DEBUG = "true"

[[redirects]]
  from = "/*"
  to = "/main"
  status = 200
